<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>
<body>
    <h1><?=$title; ?></h1>
<?php if ((isset($success)) || (isset($_GET['success']))): ?>
    <h2><?=$title; ?></h2>
    <p>You have been successfully unsubscribed from this website.</p>
<?php elseif (isset($form)): ?>
<?=$form; ?>
<?php endif; ?>
</body>

</html>
