<?php include $phireHeader; ?>
    <h1 class="members-header"><?=$title; ?> : <span id="title-span"><?=$member_name; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'members', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/members-admin/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/members-admin">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
