<?php include $phireHeader; ?>
    <h1 class="members-header"><?=$title; ?></h1>
<?php if (count($members) > 0): ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'members', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/members-admin/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/modules">Back</a></nav>
    </nav>
<?php if ($acl->isAllowed($user->role, 'members', 'remove')): ?>
    <form id="members-admins-form" action="<?=$phireUri . '/members-admin/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/members-admin?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/members-admin?sort=name';?>">Name</a></th>
                <th>URI</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'members', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'members', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_member_admins" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($members as $member): ?>
            <tr>
                <td><?=$member->id; ?></td>
                <td><?=$member->name; ?></td>
                <td><?=$member->uri; ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'members', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/members-admin/edit/' . $member->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'members', 'remove')): ?><input type="checkbox" name="rm_member_admins[]" id="rm_member_admins<?=$i++; ?>" value="<?=$member->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'members', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'members', 'add')): ?>
        <nav><a href="<?=$phireUri; ?>/members-admin/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri; ?>/modules">Back</a></nav>
    </nav>
    <p>There are currently no member configurations.</p>
<?php endif; ?>
<?php include $phireFooter; ?>