<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="robots" content="all" />

</head>
<body>
    <h1><?=$title; ?></h1>
<?php if (isset($success) && ($success)): ?>
    <p>Thank you. You have successfully registered with this website.<?php if (!($verified)): ?> Please check your email to verify your email address.<?php endif; ?></p>
<?php elseif (isset($form)): ?>
<?=$form; ?>
<?php endif; ?>
</body>

</html>
